services:
  - type: web
    name: geoserver
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GEOSERVER_ADMIN_USER
        value: admin
      - key: GEOSERVER_ADMIN_PASSWORD
        value: testing123
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: POSTGIS_HOST
        value: dpg-d82buslckfvc73f7m3j0-a
      - key: POSTGIS_PORT
        value: "5432"
      - key: POSTGIS_DB
        value: geodb_0hyd
      - key: POSTGIS_USER
        value: geodb_0hyd_user
      - key: POSTGIS_PASSWORD
        value: RLzoieV1g6cJYmi5ZUvLuVK9rxhLdCqm
      - key: POSTGIS_SCHEMA
        value: public
      - key: GEOSERVER_WORKSPACE
        value: myworkspace
      - key: RENDER_EXTERNAL_URL
        value: https://geoserver-4u2y.onrender.com
      # Added missing shapefile vars
      - key: SHAPEFILE_NAME
        value: Siricilla        # filename without .zip
      - key: SHAPEFILE_S3_URL
        value: ""               # set this to your S3 pre-signed URL, or leave blank to use COPY
