services:
  - type: web
    name: geoserver
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon

    healthCheckPath: /geoserver/web/

    disk:
      name: geoserver-data
      mountPath: /opt/geoserver/data
      sizeGB: 5

    envVars:
      - key: GEOSERVER_ADMIN_USER
        value: admin
      - key: GEOSERVER_ADMIN_PASSWORD
        generateValue: true               # ← boolean, not a string

      - key: PG_HOST
        value: dpg-d82buslckfvc73f7m3j0-a
      - key: PG_PORT
        value: "5432"
      - key: PG_DATABASE
        value: geodb_0hyd
      - key: PG_USER
        value: geodb_0hyd_user
      - key: PG_PASSWORD                  # ← key name was the password before
        value: RLzoieV1g6cJYmi5ZUvLuVK9rxhLdCqm

      - key: JAVA_OPTS
        value: >-
          -Xms128m
          -Xmx400m
          -XX:+UseG1GC
          -XX:MaxGCPauseMillis=200
          -XX:+UseStringDeduplication
          -XX:MaxMetaspaceSize=128m
          -XX:CompressedClassSpaceSize=64m
          -Djava.awt.headless=true
          -Dfile.encoding=UTF-8
          -DGEOSERVER_CSRF_DISABLED=true
          -DSTOP.PORT=8079
          -DSTOP.KEY=stopkey

      - key: GEOSERVER_DATA_DIR
        value: /opt/geoserver/data
      - key: GEOWEBCACHE_CACHE_DIR
        value: /opt/geoserver/data/gwc

databases:
  - name: geodb
    databaseName: geodb_0hyd
    user: geodb_0hyd_user
    region: oregon
    plan: free